// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ5SgyZHwCJzLog33n_4ZHeneVmk3KiU4',
    appId: '1:59126147801:web:0f969f25783b6325892cc8',
    messagingSenderId: '59126147801',
    projectId: 'auth-7d272',
    authDomain: 'auth-7d272.firebaseapp.com',
    storageBucket: 'auth-7d272.appspot.com',
    measurementId: 'G-YNGZGCP3VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHHWwKiMikrCR-BmaQ6GVrjjpQ_t1PSPo',
    appId: '1:59126147801:android:dbc13618da96927f892cc8',
    messagingSenderId: '59126147801',
    projectId: 'auth-7d272',
    storageBucket: 'auth-7d272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEL_3NmyQkMA7HmFxu4lRmdxi80aqFhLQ',
    appId: '1:59126147801:ios:1103ac951fd6ea6e892cc8',
    messagingSenderId: '59126147801',
    projectId: 'auth-7d272',
    storageBucket: 'auth-7d272.appspot.com',
    iosClientId: '59126147801-ekb4vj15lkho83oquhkdu46p0tp5n2bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEL_3NmyQkMA7HmFxu4lRmdxi80aqFhLQ',
    appId: '1:59126147801:ios:1103ac951fd6ea6e892cc8',
    messagingSenderId: '59126147801',
    projectId: 'auth-7d272',
    storageBucket: 'auth-7d272.appspot.com',
    iosClientId: '59126147801-ekb4vj15lkho83oquhkdu46p0tp5n2bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );
}
